// ============================================================
// SustainaLog — Dummy Data
// ============================================================
// すべてのフィールドが schema.js の型定義に準拠しています。
// Google Sheets 連携時はこのファイルを API レスポンスに差し替えるだけです。
//
// 依存: schema.js を先に読み込むこと
// ============================================================

'use strict';

// ────────────────────────────────────────────
// 企業マスタ（COMPANY_MASTER）
// Google Sheets シート名: companies
// ────────────────────────────────────────────
const COMPANY_MASTER = [
  {
    company_name:       'トヨタ自動車',
    ticker:             '7203',
    market:             MARKET.PRIME,
    industry:           '自動車',
    official_url:       'https://global.toyota/jp/',
    ir_url:             'https://global.toyota/jp/ir/',
    sustainability_url: 'https://global.toyota/jp/sustainability/',
    aliases:            ['Toyota', 'トヨタ'],
    icon:               '🚗',
  },
  {
    company_name:       'ソニーグループ',
    ticker:             '6758',
    market:             MARKET.PRIME,
    industry:           '電機・精密機器',
    official_url:       'https://www.sony.com/ja/',
    ir_url:             'https://www.sony.com/ja/SonyInfo/IR/',
    sustainability_url: 'https://www.sony.com/ja/SonyInfo/csr/',
    aliases:            ['Sony', 'ソニー'],
    icon:               '🎮',
  },
  {
    company_name:       'リクルートホールディングス',
    ticker:             '6098',
    market:             MARKET.PRIME,
    industry:           'サービス・HR',
    official_url:       'https://recruit-holdings.com/ja/',
    ir_url:             'https://recruit-holdings.com/ja/ir/',
    sustainability_url: 'https://recruit-holdings.com/ja/sustainability/',
    aliases:            ['Recruit', 'リクルートHD'],
    icon:               '💼',
  },
  {
    company_name:       'みずほフィナンシャルグループ',
    ticker:             '8411',
    market:             MARKET.PRIME,
    industry:           '金融・銀行',
    official_url:       'https://www.mizuho-fg.co.jp/',
    ir_url:             'https://www.mizuho-fg.co.jp/investors/',
    sustainability_url: 'https://www.mizuho-fg.co.jp/sustainability/',
    aliases:            ['みずほFG', 'みずほ銀行'],
    icon:               '🏦',
  },
  {
    company_name:       'パナソニックホールディングス',
    ticker:             '6752',
    market:             MARKET.PRIME,
    industry:           '電機・精密機器',
    official_url:       'https://holdings.panasonic/jp/',
    ir_url:             'https://holdings.panasonic/jp/corporate/ir.html',
    sustainability_url: 'https://holdings.panasonic/jp/corporate/sustainability.html',
    aliases:            ['Panasonic', 'パナソニックHD'],
    icon:               '⚡',
  },
  {
    company_name:       'ファミリーマート',
    ticker:             null,
    market:             MARKET.OTHER,
    industry:           '小売・コンビニ',
    official_url:       'https://www.family.co.jp/',
    ir_url:             null,
    sustainability_url: 'https://www.family.co.jp/sustainability.html',
    aliases:            ['FamilyMart', 'ファミマ'],
    icon:               '🏪',
  },
  {
    company_name:       'アサヒグループホールディングス',
    ticker:             '2502',
    market:             MARKET.PRIME,
    industry:           '食品・飲料',
    official_url:       'https://www.asahigroup-holdings.com/',
    ir_url:             'https://www.asahigroup-holdings.com/ir/',
    sustainability_url: 'https://www.asahigroup-holdings.com/sustainability/',
    aliases:            ['アサヒグループHD', 'Asahi'],
    icon:               '🍺',
  },
  {
    company_name:       'NTTグループ',
    ticker:             '9432',
    market:             MARKET.PRIME,
    industry:           '通信・IT',
    official_url:       'https://www.ntt.com/',
    ir_url:             'https://www.ntt.com/ir.html',
    sustainability_url: 'https://www.ntt.com/about-us/csr.html',
    aliases:            ['NTT', '日本電信電話'],
    icon:               '📡',
  },
  {
    company_name:       'キリンホールディングス',
    ticker:             '2503',
    market:             MARKET.PRIME,
    industry:           '食品・飲料',
    official_url:       'https://www.kirinholdings.com/jp/',
    ir_url:             'https://www.kirinholdings.com/jp/investors/',
    sustainability_url: 'https://www.kirinholdings.com/jp/impact/',
    aliases:            ['キリンHD', 'Kirin'],
    icon:               '🍻',
  },
  {
    company_name:       'イオングループ',
    ticker:             '8267',
    market:             MARKET.PRIME,
    industry:           '小売・コンビニ',
    official_url:       'https://www.aeon.info/',
    ir_url:             'https://www.aeon.info/ir/',
    sustainability_url: 'https://www.aeon.info/sustainability/',
    aliases:            ['イオン', 'AEON'],
    icon:               '🛒',
  },
];

// ────────────────────────────────────────────
// CSRテーマ定義（UI表示用）
// ────────────────────────────────────────────
const THEME_DEFINITIONS = [
  {
    csr_type:    CSR_TYPE.ENVIRONMENT,
    csr_subtype: CSR_SUBTYPE.CARBON_NEUTRAL,
    label:       '気候変動・脱炭素',
    count:       24,
    keywords:    ['カーボンニュートラル','RE100','TCFD','SBT','Scope3'],
    desc:        '温室効果ガス削減・RE100・カーボンオフセット・TCFD開示など気候変動対応。',
  },
  {
    csr_type:    CSR_TYPE.ENVIRONMENT,
    csr_subtype: CSR_SUBTYPE.CIRCULAR_ECONOMY,
    label:       '循環経済・廃棄物削減',
    count:       18,
    keywords:    ['プラスチックフリー','リサイクル','廃棄物ゼロ','サーキュラー'],
    desc:        'プラスチック削減・リサイクル推進・廃棄物ゼロ・サーキュラーエコノミーへの移行。',
  },
  {
    csr_type:    CSR_TYPE.ENVIRONMENT,
    csr_subtype: CSR_SUBTYPE.BIODIVERSITY,
    label:       '生物多様性',
    count:       11,
    keywords:    ['TNFD','ネイチャーポジティブ','生態系','自然資本'],
    desc:        'TNFD対応・自然資本保全・生態系サービスへの取組み。',
  },
  {
    csr_type:    CSR_TYPE.GOVERNANCE,
    csr_subtype: CSR_SUBTYPE.GREEN_FINANCE,
    label:       'ESG金融・ガバナンス',
    count:       15,
    keywords:    ['グリーンボンド','ESG投資','インパクト投資','SFDR'],
    desc:        'グリーンボンド・ESG投資・インパクト投資など金融セクターのサステナビリティ活動。',
  },
  {
    csr_type:    CSR_TYPE.EDUCATION,
    csr_subtype: CSR_SUBTYPE.DIGITAL_LITERACY,
    label:       '教育支援・人材育成',
    count:       14,
    keywords:    ['リスキリング','人的資本','D&I','奨学金','デジタル教育'],
    desc:        '従業員研修・リスキリング・次世代人材育成・インターンシップ・奨学金。',
  },
  {
    csr_type:    CSR_TYPE.ENVIRONMENT,
    csr_subtype: CSR_SUBTYPE.WATER,
    label:       '水・資源保全',
    count:       8,
    keywords:    ['AWS','水ストレス','節水','希少金属'],
    desc:        '水ストレス対応・ウォータースチュワードシップ・希少資源の節約。',
  },
  {
    csr_type:    CSR_TYPE.COMMUNITY,
    csr_subtype: null,
    label:       '地域貢献・災害支援',
    count:       10,
    keywords:    ['地域創生','被災地支援','ボランティア','共助'],
    desc:        '地域振興・被災地支援・文化財保護・地域雇用創出。',
  },
  {
    csr_type:    CSR_TYPE.DEI,
    csr_subtype: CSR_SUBTYPE.GENDER_EQUALITY,
    label:       'DEI・人権',
    count:       9,
    keywords:    ['ジェンダー平等','障がい者雇用','多様性','インクルージョン'],
    desc:        'ジェンダー平等・障がい者雇用・多様性・インクルージョンへの取組み。',
  },
];

// ────────────────────────────────────────────
// 記事ダミーデータ（DUMMY_ARTICLES）
// Google Sheets シート名: articles
// すべてのフィールドが schema.js に準拠
// ────────────────────────────────────────────
const DUMMY_ARTICLES = [
  {
    article_id:              'ART-2024-001',
    slug:                    'toyota-carbon-neutral-2050',
    company_name:            'トヨタ自動車',
    ticker:                  '7203',
    market:                  MARKET.PRIME,
    industry:                '自動車',
    source_name:             'トヨタ自動車 サステナビリティサイト',
    source_url:              'https://global.toyota/jp/sustainability/',
    official_url:            'https://global.toyota/jp/',
    ir_url:                  'https://global.toyota/jp/ir/',
    sustainability_url:      'https://global.toyota/jp/sustainability/',
    source_title:            'Toyota Carbon Neutral Roadmap 2050',
    translated_title:        'トヨタ自動車、2050年カーボンニュートラル達成に向けた新ロードマップを発表',
    summary:                 'トヨタ自動車は2050年までにカーボンニュートラルを達成するための詳細なロードマップを発表した。2030年までにEV・FCVを合計350万台以上販売する目標を掲げ、バッテリーや水素技術への投資を大幅に拡大する方針を示した。また、サプライチェーン全体でのCO2削減に向けてサプライヤーとの連携強化も明言した。',
    ai_commentary:           '本活動はパリ協定の1.5℃目標に整合する取組みと評価できます。特にサプライチェーン全体を含むScope3排出量の削減に踏み込んでいる点は、同業他社と比較しても先進的な姿勢です。水素技術との組み合わせによりトランジションリスクを分散させている点も注目に値します。ただし、中期目標（2030年）の具体的な検証手段の開示が今後の課題となるでしょう。',
    csr_type:                CSR_TYPE.ENVIRONMENT,
    csr_subtype:             CSR_SUBTYPE.CARBON_NEUTRAL,
    relation_type:           RELATION_TYPE.DIRECT,
    stakeholder_type:        STAKEHOLDER_TYPE.INVESTOR,
    classification_tags:     ['脱炭素','EV','水素','サプライチェーン','TCFD','Scope3'],
    score_social_clarity:    4,
    score_continuity:        5,
    score_business_alignment:5,
    score_specificity:       4,
    score_reference_value:   5,
    total_score:             23,
    published_at:            '2024-11-15',
    fetched_at:              '2024-11-16',
    status:                  ARTICLE_STATUS.PUBLISHED,
    publish_flag:            true,
    featured:                true,
  },
  {
    article_id:              'ART-2024-002',
    slug:                    'sony-ocean-plastic-packaging',
    company_name:            'ソニーグループ',
    ticker:                  '6758',
    market:                  MARKET.PRIME,
    industry:                '電機・精密機器',
    source_name:             'ソニーグループ CSRレポート',
    source_url:              'https://www.sony.com/ja/SonyInfo/csr/',
    official_url:            'https://www.sony.com/ja/',
    ir_url:                  'https://www.sony.com/ja/SonyInfo/IR/',
    sustainability_url:      'https://www.sony.com/ja/SonyInfo/csr/',
    source_title:            'Sony Sustainable Packaging Initiative 2025',
    translated_title:        'ソニーグループ、製品包装材の100%サステナブル素材化を2025年までに実現へ',
    summary:                 'ソニーグループは全製品の包装材を2025年度末までに100%サステナブル素材（再生紙・植物由来プラスチック・海洋プラスチック再生材など）へ切り替えると発表した。すでに国内主要製品では新素材の採用が進んでおり、海外展開も加速する。',
    ai_commentary:           '単なる「環境対応」にとどまらず、サプライヤー評価基準にサステナブル調達を組み込む点が注目されます。消費者の購買意欲にも直接訴えられるため、ブランド価値向上にも寄与する可能性が高いと見られます。',
    csr_type:                CSR_TYPE.ENVIRONMENT,
    csr_subtype:             CSR_SUBTYPE.CIRCULAR_ECONOMY,
    relation_type:           RELATION_TYPE.DIRECT,
    stakeholder_type:        STAKEHOLDER_TYPE.CUSTOMER,
    classification_tags:     ['プラスチック削減','包装材','サーキュラー','海洋プラスチック'],
    score_social_clarity:    4,
    score_continuity:        4,
    score_business_alignment:4,
    score_specificity:       3,
    score_reference_value:   4,
    total_score:             19,
    published_at:            '2024-10-22',
    fetched_at:              '2024-10-23',
    status:                  ARTICLE_STATUS.PUBLISHED,
    publish_flag:            true,
    featured:                false,
  },
  {
    article_id:              'ART-2024-003',
    slug:                    'recruit-digital-inclusion',
    company_name:            'リクルートホールディングス',
    ticker:                  '6098',
    market:                  MARKET.PRIME,
    industry:                'サービス・HR',
    source_name:             'リクルートホールディングス サステナビリティ',
    source_url:              'https://recruit-holdings.com/ja/sustainability/',
    official_url:            'https://recruit-holdings.com/ja/',
    ir_url:                  'https://recruit-holdings.com/ja/ir/',
    sustainability_url:      'https://recruit-holdings.com/ja/sustainability/',
    source_title:            'Recruit Digital Literacy Program for Job Seekers',
    translated_title:        'リクルートホールディングス、デジタルデバイド解消に向けた無料IT教育プログラムを全国展開',
    summary:                 'リクルートHDは、デジタルスキルを持たない求職者や高齢者を対象に無料のITリテラシー教育プログラムを開始した。全国47都道府県のハローワークおよびオンラインで受講可能とし、初年度10万人の受講を目指す。',
    ai_commentary:           '労働市場の「デジタル格差」は社会課題として急速に顕在化しており、本施策は自社の事業ドメイン（人材サービス）と社会貢献が直接連動するビジネスモデル型CSRの好例です。ESG投資家からの評価向上にも寄与する可能性があります。',
    csr_type:                CSR_TYPE.EDUCATION,
    csr_subtype:             CSR_SUBTYPE.DIGITAL_LITERACY,
    relation_type:           RELATION_TYPE.DIRECT,
    stakeholder_type:        STAKEHOLDER_TYPE.COMMUNITY,
    classification_tags:     ['デジタルリテラシー','デジタルデバイド','求職者支援','リスキリング'],
    score_social_clarity:    5,
    score_continuity:        4,
    score_business_alignment:5,
    score_specificity:       3,
    score_reference_value:   4,
    total_score:             21,
    published_at:            '2024-09-30',
    fetched_at:              '2024-10-01',
    status:                  ARTICLE_STATUS.PUBLISHED,
    publish_flag:            true,
    featured:                false,
  },
  {
    article_id:              'ART-2024-004',
    slug:                    'mizuho-green-bond',
    company_name:            'みずほフィナンシャルグループ',
    ticker:                  '8411',
    market:                  MARKET.PRIME,
    industry:                '金融・銀行',
    source_name:             'みずほフィナンシャルグループ サステナビリティ',
    source_url:              'https://www.mizuho-fg.co.jp/sustainability/',
    official_url:            'https://www.mizuho-fg.co.jp/',
    ir_url:                  'https://www.mizuho-fg.co.jp/investors/',
    sustainability_url:      'https://www.mizuho-fg.co.jp/sustainability/',
    source_title:            'Mizuho Green Bond Issuance 500 Billion Yen',
    translated_title:        'みずほフィナンシャルグループ、国内最大級グリーンボンド5000億円を発行',
    summary:                 'みずほFGは再生可能エネルギーや省エネ事業向けのグリーンボンドを5000億円規模で発行すると発表した。調達資金は国内外の太陽光・洋上風力発電プロジェクトへの融資に充当される。ICMAグリーンボンド原則に準拠しており、第三者検証も実施済み。',
    ai_commentary:           '金融機関によるグリーンボンド発行は、実体経済のサステナビリティ移行を金融面から支える「触媒機能」として重要です。グリーンウォッシングリスクを避けるため第三者検証を徹底している点は評価できます。',
    csr_type:                CSR_TYPE.GOVERNANCE,
    csr_subtype:             CSR_SUBTYPE.GREEN_FINANCE,
    relation_type:           RELATION_TYPE.DIRECT,
    stakeholder_type:        STAKEHOLDER_TYPE.INVESTOR,
    classification_tags:     ['グリーンボンド','ESG金融','再生可能エネルギー','ICMA','洋上風力'],
    score_social_clarity:    4,
    score_continuity:        4,
    score_business_alignment:5,
    score_specificity:       4,
    score_reference_value:   4,
    total_score:             21,
    published_at:            '2024-09-10',
    fetched_at:              '2024-09-11',
    status:                  ARTICLE_STATUS.PUBLISHED,
    publish_flag:            true,
    featured:                false,
  },
  {
    article_id:              'ART-2024-005',
    slug:                    'panasonic-biodiversity',
    company_name:            'パナソニックホールディングス',
    ticker:                  '6752',
    market:                  MARKET.PRIME,
    industry:                '電機・精密機器',
    source_name:             'パナソニック サステナビリティ',
    source_url:              'https://holdings.panasonic/jp/corporate/sustainability.html',
    official_url:            'https://holdings.panasonic/jp/',
    ir_url:                  'https://holdings.panasonic/jp/corporate/ir.html',
    sustainability_url:      'https://holdings.panasonic/jp/corporate/sustainability.html',
    source_title:            'Panasonic Biodiversity Conservation Project',
    translated_title:        'パナソニック、国内工場敷地での生物多様性保全プロジェクトを開始',
    summary:                 'パナソニックは全国15か所の工場・研究所の緑地を活用し、在来植物の保護・育成や昆虫モニタリングを行う生物多様性保全プロジェクトを開始した。TNFD（自然関連財務情報開示タスクフォース）フレームワークに基づく情報開示も進める予定。',
    ai_commentary:           'TNFDへの対応は日本企業では先進的な取組みであり、2030年のネイチャーポジティブ目標に向けた自然資本リスク管理の好事例です。従業員参加型のプログラムとしてエンゲージメント向上にも貢献する構造となっています。',
    csr_type:                CSR_TYPE.ENVIRONMENT,
    csr_subtype:             CSR_SUBTYPE.BIODIVERSITY,
    relation_type:           RELATION_TYPE.INDIRECT,
    stakeholder_type:        STAKEHOLDER_TYPE.EMPLOYEE,
    classification_tags:     ['TNFD','生物多様性','ネイチャーポジティブ','自然資本','工場緑地'],
    score_social_clarity:    4,
    score_continuity:        4,
    score_business_alignment:3,
    score_specificity:       4,
    score_reference_value:   5,
    total_score:             20,
    published_at:            '2024-08-20',
    fetched_at:              '2024-08-21',
    status:                  ARTICLE_STATUS.PUBLISHED,
    publish_flag:            true,
    featured:                false,
  },
  {
    article_id:              'ART-2024-006',
    slug:                    'familymart-food-loss',
    company_name:            'ファミリーマート',
    ticker:                  null,
    market:                  MARKET.OTHER,
    industry:                '小売・コンビニ',
    source_name:             'ファミリーマート サステナビリティ',
    source_url:              'https://www.family.co.jp/sustainability.html',
    official_url:            'https://www.family.co.jp/',
    ir_url:                  null,
    sustainability_url:      'https://www.family.co.jp/sustainability.html',
    source_title:            'FamilyMart AI Order Optimization for Food Loss Reduction',
    translated_title:        'ファミリーマート、食品ロス削減に向けAIを活用した発注最適化システムを全店導入',
    summary:                 'ファミリーマートは独自開発のAI発注支援システムを全国約16,000店舗に展開完了した。リアルタイムの天気・イベント情報と販売データを組み合わせた需要予測により、食品廃棄ロスを従来比で約20%削減することを目指す。',
    ai_commentary:           '小売業における食品ロスはサプライチェーン全体のCO2排出にも直結する重大課題です。AI活用による構造的解決策は、単発のキャンペーン型CSRとは異なり持続的な効果が期待できます。フランチャイジーへの展開が鍵となるでしょう。',
    csr_type:                CSR_TYPE.ENVIRONMENT,
    csr_subtype:             CSR_SUBTYPE.FOOD_LOSS,
    relation_type:           RELATION_TYPE.DIRECT,
    stakeholder_type:        STAKEHOLDER_TYPE.SUPPLY,
    classification_tags:     ['食品ロス','AI活用','需要予測','廃棄削減','コンビニ'],
    score_social_clarity:    4,
    score_continuity:        5,
    score_business_alignment:5,
    score_specificity:       4,
    score_reference_value:   4,
    total_score:             22,
    published_at:            '2024-08-05',
    fetched_at:              '2024-08-06',
    status:                  ARTICLE_STATUS.PUBLISHED,
    publish_flag:            true,
    featured:                false,
  },
  {
    article_id:              'ART-2024-007',
    slug:                    'asahi-water-stewardship',
    company_name:            'アサヒグループホールディングス',
    ticker:                  '2502',
    market:                  MARKET.PRIME,
    industry:                '食品・飲料',
    source_name:             'アサヒグループ サステナビリティ',
    source_url:              'https://www.asahigroup-holdings.com/sustainability/',
    official_url:            'https://www.asahigroup-holdings.com/',
    ir_url:                  'https://www.asahigroup-holdings.com/ir/',
    sustainability_url:      'https://www.asahigroup-holdings.com/sustainability/',
    source_title:            'Asahi Group Water Stewardship Strategy 2030',
    translated_title:        'アサヒグループ、水資源保全に向けた「ウォーター・スチュワードシップ」戦略を策定',
    summary:                 'アサヒグループHDは2030年に向けた水資源保全戦略を発表。水ストレスの高い地域にある工場での取水量削減、地域コミュニティとの集水域管理、そしてAWS（アライアンス・フォー・ウォーター・スチュワードシップ）認証取得を進める。',
    ai_commentary:           '飲料業界にとって水は事業基盤そのものであり、水リスク管理はビジネス継続性に直結します。AWSなどの国際的な認証基準を活用することで、グローバル投資家への信頼性も担保できる設計となっています。',
    csr_type:                CSR_TYPE.ENVIRONMENT,
    csr_subtype:             CSR_SUBTYPE.WATER,
    relation_type:           RELATION_TYPE.DIRECT,
    stakeholder_type:        STAKEHOLDER_TYPE.INVESTOR,
    classification_tags:     ['水資源','ウォータースチュワードシップ','AWS','取水量削減','飲料'],
    score_social_clarity:    4,
    score_continuity:        5,
    score_business_alignment:5,
    score_specificity:       3,
    score_reference_value:   4,
    total_score:             21,
    published_at:            '2024-07-18',
    fetched_at:              '2024-07-19',
    status:                  ARTICLE_STATUS.PUBLISHED,
    publish_flag:            true,
    featured:                false,
  },
  {
    article_id:              'ART-2024-008',
    slug:                    'ntt-renewable-energy-100',
    company_name:            'NTTグループ',
    ticker:                  '9432',
    market:                  MARKET.PRIME,
    industry:                '通信・IT',
    source_name:             'NTTグループ CSR・環境',
    source_url:              'https://www.ntt.com/about-us/csr.html',
    official_url:            'https://www.ntt.com/',
    ir_url:                  'https://www.ntt.com/ir.html',
    sustainability_url:      'https://www.ntt.com/about-us/csr.html',
    source_title:            'NTT Group RE100 Declaration and Renewable Energy Roadmap',
    translated_title:        'NTTグループ、2030年までに使用電力の100%を再生可能エネルギーで賄う目標を設定',
    summary:                 'NTTグループはRE100に加盟し、2030年までに国内外のグループ全体で使用電力を再生可能エネルギー100%にする目標を設定した。自社での太陽光・風力発電所の開発に加え、コーポレートPPAによる長期調達も組み合わせる。データセンターの省エネ化も並行して推進する。',
    ai_commentary:           '通信・データセンター業界は世界の電力消費の2〜3%を占めるとされており、大規模なRE100達成は業界全体への波及効果が期待できます。自社開発＋PPA組み合わせ戦略は調達リスク分散の観点からも適切な設計です。',
    csr_type:                CSR_TYPE.ENVIRONMENT,
    csr_subtype:             CSR_SUBTYPE.RENEWABLE_ENERGY,
    relation_type:           RELATION_TYPE.DIRECT,
    stakeholder_type:        STAKEHOLDER_TYPE.INVESTOR,
    classification_tags:     ['RE100','再生可能エネルギー','データセンター','PPA','省エネ'],
    score_social_clarity:    4,
    score_continuity:        5,
    score_business_alignment:5,
    score_specificity:       4,
    score_reference_value:   4,
    total_score:             22,
    published_at:            '2024-06-28',
    fetched_at:              '2024-06-29',
    status:                  ARTICLE_STATUS.PUBLISHED,
    publish_flag:            true,
    featured:                false,
  },
  // ステータスサンプル（承認待ち）
  {
    article_id:              'ART-2024-009',
    slug:                    'kirin-social-impact',
    company_name:            'キリンホールディングス',
    ticker:                  '2503',
    market:                  MARKET.PRIME,
    industry:                '食品・飲料',
    source_name:             'キリングループ サステナビリティ',
    source_url:              'https://www.kirinholdings.com/jp/impact/',
    official_url:            'https://www.kirinholdings.com/jp/',
    ir_url:                  'https://www.kirinholdings.com/jp/investors/',
    sustainability_url:      'https://www.kirinholdings.com/jp/impact/',
    source_title:            'Kirin Social Impact Framework 2024',
    translated_title:        'キリングループ、アルコール関連問題への社会的責任方針を強化',
    summary:                 'キリングループは「CSV（共有価値の創造）」経営の一環として、適正飲酒推進・アルコール依存症支援などの活動を強化した。業界団体との連携や医療機関への支援を通じ、飲酒に起因する社会課題の軽減に取り組む。',
    ai_commentary:           '自社製品のリスクを正面から認め、社会課題解決に向けて取り組む姿勢は評価できます。国際的なResponsible Drinkingフレームワークへの準拠が今後の課題です。',
    csr_type:                CSR_TYPE.HEALTH,
    csr_subtype:             null,
    relation_type:           RELATION_TYPE.DIRECT,
    stakeholder_type:        STAKEHOLDER_TYPE.COMMUNITY,
    classification_tags:     ['健康経営','アルコール','CSV','社会課題'],
    score_social_clarity:    4,
    score_continuity:        3,
    score_business_alignment:4,
    score_specificity:       2,
    score_reference_value:   3,
    total_score:             16,
    published_at:            '2024-06-01',
    fetched_at:              '2024-11-20',
    status:                  ARTICLE_STATUS.PENDING_REVIEW,
    publish_flag:            false,
    featured:                false,
  },
];

// ────────────────────────────────────────────
// アクセサ関数
// ────────────────────────────────────────────

/** 公開済み記事のみ返す */
function getPublishedArticles() {
  return DUMMY_ARTICLES.filter(a => a.status === ARTICLE_STATUS.PUBLISHED && a.publish_flag);
}

/** slug で記事を取得 */
function getArticleBySlug(slug) {
  return DUMMY_ARTICLES.find(a => a.slug === slug) || null;
}

/** csr_type でフィルタ */
function getArticlesByCsrType(csrType) {
  return getPublishedArticles().filter(a => a.csr_type === csrType);
}

/** 企業名で記事を取得 */
function getArticlesByCompany(companyName) {
  return getPublishedArticles().filter(a => a.company_name === companyName);
}

/** 企業名でマスタ取得 */
function getCompanyByName(companyName) {
  return COMPANY_MASTER.find(c =>
    c.company_name === companyName ||
    (c.aliases && c.aliases.includes(companyName))
  ) || null;
}

/** 記事一覧用: 後方互換のため旧フィールド名にマッピングするアダプタ */
function adaptArticleForUI(article) {
  return {
    ...article,
    // 旧 data.js との後方互換
    title:     article.translated_title,
    company:   article.company_name,
    themes:    [article.csr_type, article.csr_subtype].filter(Boolean),
    aiComment: article.ai_commentary,
    sourceUrl: article.source_url,
    sourceName:article.source_name,
    publishedAt: article.published_at,
  };
}

/** 全公開記事をUI用アダプタ経由で返す */
function getArticlesForUI() {
  return getPublishedArticles().map(adaptArticleForUI);
}
